"""otodom pictures

Revision ID: 32f9fe4693dc
Revises: b54b3df9ec76
Create Date: 2022-08-18 09:57:30.574006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f9fe4693dc'
down_revision = 'b54b3df9ec76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('picture', sa.String(length=256), nullable=True))
    op.add_column('house', sa.Column('picture', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house', 'picture')
    op.drop_column('flat', 'picture')
    # ### end Alembic commands ###
