"""images

Revision ID: 6d940062fe60
Revises: b54b3df9ec76
Create Date: 2022-08-19 10:33:38.017938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d940062fe60'
down_revision = 'b54b3df9ec76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('picture1', sa.String(length=256), nullable=True))
    op.add_column('flat', sa.Column('picture2', sa.String(length=256), nullable=True))
    op.add_column('flat', sa.Column('picture3', sa.String(length=256), nullable=True))
    op.add_column('flat', sa.Column('picture4', sa.String(length=256), nullable=True))
    op.add_column('flat', sa.Column('picture5', sa.String(length=256), nullable=True))
    op.add_column('flat', sa.Column('picture6', sa.String(length=256), nullable=True))
    op.add_column('flat', sa.Column('picture7', sa.String(length=256), nullable=True))
    op.add_column('flat', sa.Column('picture8', sa.String(length=256), nullable=True))
    op.add_column('house', sa.Column('picture1', sa.String(length=256), nullable=True))
    op.add_column('house', sa.Column('picture2', sa.String(length=256), nullable=True))
    op.add_column('house', sa.Column('picture3', sa.String(length=256), nullable=True))
    op.add_column('house', sa.Column('picture4', sa.String(length=256), nullable=True))
    op.add_column('house', sa.Column('picture5', sa.String(length=256), nullable=True))
    op.add_column('house', sa.Column('picture6', sa.String(length=256), nullable=True))
    op.add_column('house', sa.Column('picture7', sa.String(length=256), nullable=True))
    op.add_column('house', sa.Column('picture8', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house', 'picture8')
    op.drop_column('house', 'picture7')
    op.drop_column('house', 'picture6')
    op.drop_column('house', 'picture5')
    op.drop_column('house', 'picture4')
    op.drop_column('house', 'picture3')
    op.drop_column('house', 'picture2')
    op.drop_column('house', 'picture1')
    op.drop_column('flat', 'picture8')
    op.drop_column('flat', 'picture7')
    op.drop_column('flat', 'picture6')
    op.drop_column('flat', 'picture5')
    op.drop_column('flat', 'picture4')
    op.drop_column('flat', 'picture3')
    op.drop_column('flat', 'picture2')
    op.drop_column('flat', 'picture1')
    # ### end Alembic commands ###
