"""init

Revision ID: eca0d6f5f052
Revises: 
Create Date: 2022-07-25 11:19:07.263212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca0d6f5f052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flat',
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('id_scrap', sa.Integer(), nullable=True),
    sa.Column('for_sale', sa.Boolean(), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('district', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=32), nullable=True),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('number_of_rooms', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=32), nullable=True),
    sa.Column('price_per_m2', sa.String(length=32), nullable=True),
    sa.Column('rent_price', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('flat_id'),
    sa.UniqueConstraint('id_scrap')
    )
    op.create_index(op.f('ix_flat_flat_id'), 'flat', ['flat_id'], unique=False)
    op.create_table('house',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('id_scrap', sa.Integer(), nullable=True),
    sa.Column('for_sale', sa.Boolean(), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('district', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=32), nullable=True),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('number_of_rooms', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=32), nullable=True),
    sa.Column('price_per_m2', sa.String(length=32), nullable=True),
    sa.Column('rent_price', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('house_id'),
    sa.UniqueConstraint('id_scrap')
    )
    op.create_index(op.f('ix_house_house_id'), 'house', ['house_id'], unique=False)
    op.create_table('flat_info',
    sa.Column('flat_info_id', sa.Integer(), nullable=False),
    sa.Column('flat_floor', sa.String(length=16), nullable=True),
    sa.Column('bills_monthly', sa.String(length=16), nullable=True),
    sa.Column('finish_condition', sa.String(length=32), nullable=True),
    sa.Column('balcony_garden', sa.String(length=32), nullable=True),
    sa.Column('parking_spot', sa.String(length=32), nullable=True),
    sa.Column('heating', sa.String(length=32), nullable=True),
    sa.Column('advertiser', sa.String(length=32), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('year_of_construction', sa.Integer(), nullable=True),
    sa.Column('type_of_building', sa.String(length=32), nullable=True),
    sa.Column('windows', sa.String(length=32), nullable=True),
    sa.Column('walls_material', sa.String(length=32), nullable=True),
    sa.Column('elevator', sa.Boolean(), nullable=True),
    sa.Column('utilities_supplied', sa.String(length=128), nullable=True),
    sa.Column('security_stuff', sa.String(length=128), nullable=True),
    sa.Column('equipment', sa.String(length=128), nullable=True),
    sa.Column('property_form', sa.String(length=32), nullable=True),
    sa.Column('market', sa.String(length=32), nullable=True),
    sa.Column('deposit', sa.String(length=32), nullable=True),
    sa.Column('available_for_students', sa.Boolean(), nullable=True),
    sa.Column('extras', sa.String(length=128), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['flat.flat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flat_info_id')
    )
    op.create_index(op.f('ix_flat_info_flat_info_id'), 'flat_info', ['flat_info_id'], unique=False)
    op.create_table('house_info',
    sa.Column('house_info_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=True),
    sa.Column('deposit', sa.String(length=32), nullable=True),
    sa.Column('plot_area', sa.String(length=32), nullable=True),
    sa.Column('type_of_building', sa.String(length=32), nullable=True),
    sa.Column('heating', sa.String(length=32), nullable=True),
    sa.Column('finish_condition', sa.String(length=32), nullable=True),
    sa.Column('year_of_construction', sa.Integer(), nullable=True),
    sa.Column('parking_spot', sa.String(length=32), nullable=True),
    sa.Column('bills_monthly', sa.String(length=32), nullable=True),
    sa.Column('advertiser', sa.String(length=32), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('walls_material', sa.String(length=32), nullable=True),
    sa.Column('windows', sa.String(length=32), nullable=True),
    sa.Column('number_of_floors', sa.Integer(), nullable=True),
    sa.Column('holiday_house', sa.Boolean(), nullable=True),
    sa.Column('roof_type', sa.String(length=32), nullable=True),
    sa.Column('roofing_type', sa.String(length=32), nullable=True),
    sa.Column('attic', sa.String(length=32), nullable=True),
    sa.Column('utilities_supplied', sa.String(length=128), nullable=True),
    sa.Column('security_stuff', sa.String(length=128), nullable=True),
    sa.Column('fence', sa.String(length=32), nullable=True),
    sa.Column('drive_access', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('extras', sa.String(length=128), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.house_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('house_info_id')
    )
    op.create_index(op.f('ix_house_info_house_info_id'), 'house_info', ['house_info_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_house_info_house_info_id'), table_name='house_info')
    op.drop_table('house_info')
    op.drop_index(op.f('ix_flat_info_flat_info_id'), table_name='flat_info')
    op.drop_table('flat_info')
    op.drop_index(op.f('ix_house_house_id'), table_name='house')
    op.drop_table('house')
    op.drop_index(op.f('ix_flat_flat_id'), table_name='flat')
    op.drop_table('flat')
    # ### end Alembic commands ###
